name: Docker Compose Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images
      env:
        MARIADB_DATA_VOLUME: ${{vars.MARIADB_DATA_VOLUME}}
        MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
        MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
        MYSQL_USER: ${{secrets.MYSQL_USER}}
        MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      run: |
        echo $(pwd);
        echo "mariadb data: $MARIADB_DATA_VOLUME"
        docker-compose build;

    - name: Docker Compose Up
      env:
        MARIADB_DATA_VOLUME: ${{vars.MARIADB_DATA_VOLUME}}
        MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
        MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
        MYSQL_USER: ${{secrets.MYSQL_USER}}
        MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      run: |
        echo $(pwd);
        echo "mariadb data: $MARIADB_DATA_VOLUME"
        docker-compose up -d;
