name: Docker Compose Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images
      run: |
        echo $(pwd);
        docker-compose build;

    - name: Docker Compose Up
      run: |
        echo $(pwd);
        docker-compose up -d;
